### Register User


POST http://localhost:5000/auth/users
Content-Type: application/json

{
    "firstName":"author4",
    "lastName":" ",
    "email":"author4@mail.com",
    "role":"AUTHOR",
    "password":"author4",
    "profileImageUrl":"https://example.com/avatars.user.png"
}

### Login 


POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"author4@mail.com",
    "password":"author4"
}

### Logout 


GET http://localhost:5000/auth/logout

### Create new Article


POST http://localhost:5000/author-api/article
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjNkYWViMGE1ZWZhODIyMDQ5OWE1MiIsImVtYWlsIjoiYXV0aG9yM0BtYWlsLmNvbSIsInJvbGUiOiJBVVRIT1IiLCJpYXQiOjE3NzM0NTk1MDQsImV4cCI6MTc3MzQ2MzEwNH0.vU3VTdROP4GkLT2prnrsZDt_jIRwtjkm7oaQK7W98qI; Path=/; HttpOnly; SameSite=Lax

{
    "author":"69b4e0e71c7ee699e31a2ea1",
    "title":"Article-1 by Author 4",
    "category":"Programming 1",
    "content":"Test article 1 on programming in Java",
    "comments":[{
        "user":"69b3cd51fd45764b9a6e1402",
        "comment":"Very useful"
    }]
}

### Read own articles


GET http://localhost:5000/author-api/articles



### Update article


PUT http://localhost:5000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b4da2512c6352c489ea93a",
    "title":"Updated Article-5 by Author 3",
    "category":"Programming in Python",
    "content":"Test article on programming with updates",
    "comments":[{
        "user":"69b3cd51fd45764b9a6e1402",
        "comment":"Very useful"
    }]
}


### Delete/restore an article by article Id(soft delete)


PATCH http://localhost:5000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b4da2512c6352c489ea93a",
    "isArticleActive":true
}